<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="7" total="10" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-27T16:06:52 IST" name="LoanDepartment" finished-at="2024-11-27T16:06:52 IST" duration-ms="78">
    <groups>
      <group name="smoke">
        <method signature="day1.SecondTest()[pri:0, instance:test.day1@14555e0a]" name="SecondTest" class="test.day1"/>
        <method signature="day2.ploan()[pri:0, instance:test.day2@78123e82]" name="ploan" class="test.day2"/>
        <method signature="day4.WebloginHomeloan()[pri:0, instance:test.day4@67c33749]" name="WebloginHomeloan" class="test.day4"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2024-11-27T16:06:52 IST" name="Personal Loan " finished-at="2024-11-27T16:06:52 IST" duration-ms="78">
      <class name="test.day4">
        <test-method signature="WebloginHomeloan()[pri:0, instance:test.day4@67c33749]" started-at="2024-11-27T16:06:52 IST" name="WebloginHomeloan" finished-at="2024-11-27T16:06:52 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebloginHomeloan -->
      </class> <!-- test.day4 -->
      <class name="test.day2">
        <test-method signature="ploan()[pri:0, instance:test.day2@78123e82]" started-at="2024-11-27T16:06:52 IST" name="ploan" finished-at="2024-11-27T16:06:52 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ploan -->
      </class> <!-- test.day2 -->
      <class name="test.day1">
        <test-method signature="SecondTest()[pri:0, instance:test.day1@14555e0a]" started-at="2024-11-27T16:06:52 IST" name="SecondTest" finished-at="2024-11-27T16:06:52 IST" duration-ms="15" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at test.day1.SecondTest(day1.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SecondTest -->
      </class> <!-- test.day1 -->
    </test> <!-- Personal Loan  -->
    <test started-at="2024-11-27T16:06:52 IST" name="Car Loan" finished-at="2024-11-27T16:06:52 IST" duration-ms="9">
    </test> <!-- Car Loan -->
  </suite> <!-- LoanDepartment -->
</testng-results>
