<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-AFT8QP2" failures="1" tests="3" name="Personal Loan " time="0.078" errors="0" timestamp="2024-11-27T16:06:52 IST">
  <testcase classname="test.day1" name="SecondTest" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.SecondTest(day1.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- SecondTest -->
  <testcase classname="test.day2" name="ploan" time="0.002"/>
  <testcase classname="test.day4" name="WebloginHomeloan" time="0.001"/>
  <testcase classname="test.day4" name="MobileloginHomeloan" time="0.0">
    <ignored/>
  </testcase> <!-- MobileloginHomeloan -->
  <testcase classname="test.day4" name="APIloginHomeloan" time="0.0">
    <ignored/>
  </testcase> <!-- APIloginHomeloan -->
  <testcase classname="test.day1" name="Demo" time="0.0">
    <ignored/>
  </testcase> <!-- Demo -->
</testsuite> <!-- Personal Loan  -->
